services:

  spotify-like-me: 
    build: .
    container_name: spotify-like-me
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT:-12345}:8080
      - 9229:9229
    command: npm run start:development